### PR TITLE
check number if string

### PR DESCRIPTION
**Pull request by samin**

### CODE REVIEW

**Comment by vspedr** [comment]
Hi @samin and @ivan05almeida! Firstly, thanks for the PR! Would you please share the motivation for this change? I'm thinking of a few enhancements for this module, maybe we could come out with better solutions for your use cases :)

**Comment by ivan05almeida** [comment]
Actually, I was trying to send a specific message to each recipient of my message, to do something like this, I should be able to use the "sendBulk" and pass something like this: 

```
{
  "messages":[
    {
      "destination":"5519900001111",
      "messageText":"First message"
    },
    {
      "destination":"5519900002222"
    },
    {
      "destination":"5519900003333",
      "messageText":"Third message"
    }
  ],
  "defaultValues":{
    "messageText":"Default message"
  }
}
```

But, until now, the "sendBulk" was only was sending the same message to the recipients' numbers passed in the Array. And then to be able to send a specific message, the simplest way was, if I pass an object, try to send it...

So in this case, I will be able to send something like this:
```
movile_client.sendBulk([{
      "destination":"5519900001111",
      "messageText":"First message"
    }, "5519900002222", {
      "destination":"5519900003333",
      "messageText":"Third message"
    }], 'Defult message')
```

**Comment by vspedr** [comment]
Got it, this is very useful feature indeed. Later today I will release your patch into npm so you can keep using it as is without having to install from github, meanwhile I can work on it and a couple more features.

**Comment by ivan05almeida** [comment]
For whatever you need, I'll be glad to help!

**Comment by vspedr** [comment]
`movile-messaging@1.2.0-rc.1` is released :) make sure to upgrade

**Pull request merged**
